esphome:
  name: "bme280-dormitor-2-g"

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "khTmptQ7yYhvP5yxwxTQOSNPs/RK4x+twiKqYqwO900="

ota:
  - platform: esphome
    password: "c41e4c28c643ea2045016586d9ad3ecc"


wifi:
  networks:
    - ssid: !secret wifi_ssid_ext
      password: !secret wifi_password
    - ssid: !secret wifi_ssid_nou
      password: !secret wifi_password_nou  
    - ssid: !secret wifi_ssid_ext_nou
      password: !secret wifi_password_nou


i2c:
  sda: D2
  scl: D1
  scan: true
  id: bus_a
  frequency: 100kHz


sensor:
  - platform: bme280_i2c
    temperature:
      name: "Temp. Dormitor 2 G"
      oversampling: 16x
      filters:
      - calibrate_linear:
          - 0.0 -> 0.0
          - 22.5 -> 21.2
    pressure:
      name: "Pres. Dormitor 2 G"
    humidity:
      name: "Umid. Dormitor 2 G"
    address: 0x76
    update_interval: 30s
    
    