esphome:
  name: radar-exterior


esp8266:
  board: d1_mini

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "khTmptQ7yYhvP5yxwxTQOSNPs/RK4x+twiKqYqwO900="
  

ota:
  - platform: esphome
    password: "b108ebea21a5671e665c0bcf35350437"

wifi:
  networks:
    - ssid: !secret wifi_ssid_nou
      password: !secret wifi_password_nou  
    - ssid: !secret wifi_ssid_ext_nou
      password: !secret wifi_password_nou
    - ssid: !secret wifi_ssid_d_link
      password: !secret wifi_password_nou
    - ssid: !secret wifi_ssid_ext_3
      password: !secret wifi_password_nou




uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2410:
  
binary_sensor:
  - platform: gpio
    pin: GPIO12
    name: GPIO Out pin curte atelier
    device_class: 'presence'
      
