esphome:
  name: use-acces-1

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "khTmptQ7yYhvP5yxwxTQOSNPs/RK4x+twiKqYqwO900="

ota:
  - platform: esphome
    password: "c41e4c28c643ea2045016586d9ad3ecc"

wifi:
  networks:
    - ssid: !secret wifi_ssid_nou
      password: !secret wifi_password_nou  
    - ssid: !secret wifi_ssid_ext_nou
      password: !secret wifi_password_nou


binary_sensor:
  - platform: gpio
    id: "releu_use_acces_1"
    pin:
      number: 10
      mode:
        input: true
        pullup: false
    name: "Releu Use Acces 1"


    